/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pbdco.vueorga;

import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import pbdco.BDAccessEx;
import pbdco.Code;
import pbdco.partie.ControleurPartie;
import pbdco.partie.EtatsPartie;
import pbdco.tournois.PreparationTour;
import pbdco.tournois.Tournoi;

/**
 *
 * @author livingstonehgs
 */
public class VueMatchsJoueur extends javax.swing.JFrame {

    /**
     * Creates new form VueMatchsJoueur
     */
    public VueMatchsJoueur() throws BDAccessEx {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        numeroJoueur = new javax.swing.JTextField();
        okButton = new javax.swing.JButton();
        aJouer = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        joueursAAfronter = new javax.swing.JComboBox<>();
        jouerMatch = new javax.swing.JButton();
        joues = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        joueursAffrontes = new javax.swing.JComboBox<>();
        revoirMatch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Votre numéro de joueur :");

        numeroJoueur.setText("#");
        numeroJoueur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroJoueurActionPerformed(evt);
            }
        });

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(numeroJoueur, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(okButton)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(numeroJoueur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(okButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Matchs à jouer");

        joueursAAfronter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No Item" }));
        joueursAAfronter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joueursAAfronterActionPerformed(evt);
            }
        });

        jouerMatch.setText("Jouer le match");
        jouerMatch.setActionCommand("jouer");
        jouerMatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jouerMatchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout aJouerLayout = new javax.swing.GroupLayout(aJouer);
        aJouer.setLayout(aJouerLayout);
        aJouerLayout.setHorizontalGroup(
            aJouerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aJouerLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(aJouerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(joueursAAfronter, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aJouerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jouerMatch)
                .addGap(19, 19, 19))
        );
        aJouerLayout.setVerticalGroup(
            aJouerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aJouerLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(joueursAAfronter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jouerMatch)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jLabel3.setText("Matchs joués");

        joueursAffrontes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No Item" }));

        revoirMatch.setText("Revoir le match");

        javax.swing.GroupLayout jouesLayout = new javax.swing.GroupLayout(joues);
        joues.setLayout(jouesLayout);
        jouesLayout.setHorizontalGroup(
            jouesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jouesLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jouesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jouesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(joueursAffrontes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jouesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(revoirMatch, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jouesLayout.setVerticalGroup(
            jouesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jouesLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(joueursAffrontes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(revoirMatch)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(aJouer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(joues, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aJouer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(joues, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numeroJoueurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroJoueurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroJoueurActionPerformed

    private void joueursAAfronterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joueursAAfronterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_joueursAAfronterActionPerformed

    private void jouerMatchActionPerformed(java.awt.event.ActionEvent evt) throws BDAccessEx {//GEN-FIRST:event_jouerMatchActionPerformed
        // TODO add your handling code here:
        PreparationTour prep = new PreparationTour(false);
        String choix = (String) joueursAAfronter.getSelectedItem();
        String[] newString = choix.split(" ");
        ControleurPartie controlePart = new ControleurPartie( newString[2], newString[3], new Code(Integer.parseInt(newString[0])), EtatsPartie.JOUER_RENCONTRE);
        controlePart.initPlateau(prep.getTour(), new Code(Integer.parseInt(newString[0])));
    }//GEN-LAST:event_jouerMatchActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed

        Code codeJoueur = new Code(Integer.parseInt(numeroJoueur.getText()));
        try {
            Code[] codeAJouer = new Tournoi().recupererLesCodesRencontresAJouer(codeJoueur);
            Code[] codeJouer = new Tournoi().recupererLesCodesRencontresDejaJouer(codeJoueur);


            if(codeAJouer != null){
                String[][] rencontresAJouer = new Tournoi().recupRencontresAJouer(codeJoueur);
                System.out.println("le tableaux des joueurs a jouer "+ Arrays.deepToString(rencontresAJouer));
                System.out.println("le tableaux des coderencontres "+ Arrays.toString(codeAJouer));
                for(int i = 0;i<rencontresAJouer.length; i++) {
                    joueursAAfronter.addItem(String.valueOf(codeAJouer[i].getValue()) + " " + rencontresAJouer[i][0] + rencontresAJouer[i][1]); //Affiche nom et prénom dans le menu déroulant
                }
            }

            if(codeJouer != null){
                String[][] rencontresJouees = new Tournoi().recupRencontresDejaJouer(codeJoueur);
                for(int i = 0;i<rencontresJouees.length; i++) {
                    joueursAAfronter.addItem(String.valueOf(codeJouer[i].getValue()) + " " + rencontresJouees[i][0] + rencontresJouees[i][1]); //Affiche nom et prénom dans le menu déroulant

                }
            }
        } catch (BDAccessEx ex) {
            Logger.getLogger(VueMatchsJoueur.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Votre code joueur n'existe pas dans la bAAAse");
        }


    }//GEN-LAST:event_okButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VueMatchsJoueur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VueMatchsJoueur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VueMatchsJoueur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VueMatchsJoueur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new VueMatchsJoueur().setVisible(true);
                } catch (BDAccessEx ex) {
                    Logger.getLogger(VueMatchsJoueur.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aJouer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jouerMatch;
    private javax.swing.JPanel joues;
    private javax.swing.JComboBox<String> joueursAAfronter;
    private javax.swing.JComboBox<String> joueursAffrontes;
    private javax.swing.JTextField numeroJoueur;
    private javax.swing.JButton okButton;
    private javax.swing.JButton revoirMatch;
    // End of variables declaration//GEN-END:variables
}
